# Generated by Django 4.0.4 on 2022-05-26 17:13

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields
import mapa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=7, validators=[mapa.models.Regiao.valida_cor])),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstabelecimento',
            fields=[
                ('n', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('geometria', djgeojson.fields.PolygonField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('cnes', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('localizacao', djgeojson.fields.PointField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.municipio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.tipoestabelecimento')),
            ],
        ),
    ]
