# Generated by Django 4.0.4 on 2022-05-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('chave', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('referencia', models.DateField()),
                ('atendimentos', models.IntegerField()),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.doenca')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.municipio')),
            ],
        ),
    ]
