# Generated by Django 4.0.4 on 2022-05-24 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='municipio',
            field=models.ForeignKey(default=4200051, on_delete=django.db.models.deletion.DO_NOTHING, to='mapa.municipio'),
            preserve_default=False,
        ),
    ]
